---
title: "SeaDoc Phylogenetic Trees"
author: "Ashley Tseng"
date: "January 7, 2022"
output: 
  html_document:
    toc: true # table of content
    toc_depth: 6  # upto three depths of headings
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(ggplot2)
library(ggtree)
library(ape)

#library(seqinr)
#library(phangorn)
#library(phytools)
#library(ggmsa)
#library(igraph)
#library(purrr)
#library(tibble)
#library(Biostrings)
library(treeio)

setwd("/Users/ashleytseng/OneDrive - UW/UW PhD/BEBTEH/SeaDoc AMR Phylogenetics")
```


```{r my_workflow}
# Read in metadata
metadata = read_excel("/Users/ashleytseng/OneDrive - UW/UW PhD/BEBTEH/SeaDoc AMR Phylogenetics/Metadata/Final/Clean/seadoc_metadata_wgs only.xlsx", range = "B1:T342") %>% 
  janitor::clean_names()
class(metadata)

# Read in .newick file
#full_tree = read.newick("seadoc_snps.newick")
full_tree = read.tree("/Users/ashleytseng/Desktop/BEBTEH/01-06-2022/BEBTEH/seadoc_snps.newick")

#st10_tree = read.newick("seadoc_st10.newick")
#st131_tree = read.newick("seadoc_st131.newick")
# View tree (unrooted)
ggtree(full_tree)
#ggtree(st10_tree)
#ggtree(st131_tree)

# Root tree
full_tree = root(full_tree, "Reference") 
is.rooted(full_tree)
#st10_tree = root(st10_tree, "Reference") 
#is.rooted(st10_tree)
#st131_tree = root(st131_tree, "Reference") 
#is.rooted(st131_tree)
# View tree (rooted)
ggtree(full_tree)
#ggtree(tree, branch.length='none')
#ggtree(st10_tree)
#ggtree(st131_tree)


# Attach metadata for full tree
full_data = tibble(srr_id = full_tree$tip.label)

full_data = merge(full_data, metadata, by = "srr_id", all.x = TRUE)

# Add details for K-12 reference strain
full_data = full_data %>% 
  mutate(srr_id = case_when(srr_id == "Reference" ~ "SRR10971019",
                            TRUE ~ srr_id))
full_data = full_data %>% 
  mutate(project_id = case_when(srr_id == "SRR10971019" ~ "K-12 Reference Strain",
                                TRUE ~ project_id))
full_data = full_data %>% 
  mutate(specimen_source = case_when(srr_id == "SRR10971019" ~ "Human",
                                     TRUE ~ specimen_source))

# Attach metadata for ST10 tree
#st10_data = tibble(SRR_id = st10_tree$tip.label)
#st10_data = merge(st10_data, metadata, by = "SRR_id", all.x = TRUE)
# Attach metadata for ST131 tree
#st131_data = tibble(SRR_id = st131_tree$tip.label)
#st131_data = merge(st131_data, metadata, by = "SRR_id", all.x = TRUE)

# Full phylogenetic tree
full_phylotree = ggtree(full_tree)
#p = ggtree(tree, branch.length='none')
# With tip labels and colored by ST type 
full_phylotree %<+% full_data + geom_tiplab(aes(label = project_id), size = 0.5) + geom_tippoint(aes(color = specimen_source)) #too much
# Without tip labels
full_phylotree %<+% full_data + geom_tippoint(aes(color = specimen_source)) #use this
#full_phylotree + geom_text(aes(label=label), size=3, color="purple", hjust=-0.3)
#gzoom(full_phylotree, focus, subtree = TRUE, widths = c(0.3, 0.7)) #gzoom function is defunct

# Sub-trees
sub_tree = tree_subset(full_tree, node = "SRR12584072", levels_back = 6) #create subtree based on SRR12584072 seal fecal sample (AN0107)
ggtree(sub_tree) %<+% full_data + 
  geom_tiplab(aes(label = wgs_mlst)) + 
  geom_tippoint(aes(color = specimen_source)) +
  geom_treescale() +
  theme(legend.position = "bottom", 
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10)) +
  ggtitle("Phylogenetic Tree Subsetted to Evergreen Rotary Park Seal Fecal Sample (AN0107)")

sub_tree = tree_subset(full_tree, node = "SRR12584072", levels_back = 4) #create subtree based on SRR12584072 seal fecal sample (AN0107)
ggtree(sub_tree) %<+% full_data + 
  geom_tiplab(aes(label = wgs_mlst)) + 
  geom_tippoint(aes(color = specimen_source)) +
  geom_treescale() +
  theme(legend.position = "bottom", 
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10)) +
  ggtitle("Phylogenetic Tree Subsetted to Evergreen Rotary Park Seal Fecal Sample (AN0107)")



sub_tree = tree_subset(full_tree, node = "SRR12584072", levels_back = 6) #create subtree based on SRR12584072 seal fecal sample (AN0107)
ggtree(sub_tree) %<+% full_data + 
  geom_tiplab(aes(label = project_id)) + 
  geom_tippoint(aes(color = specimen_source)) +
  geom_treescale() +
  theme(legend.position = "bottom", 
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10)) +
  ggtitle("Phylogenetic Tree Subsetted to Evergreen Rotary Park Seal Fecal Sample (AN0107)")

sub_tree = tree_subset(full_tree, node = "SRR12584072", levels_back = 6) #create subtree based on SRR12584072 seal fecal sample (AN0107)
ggtree(sub_tree) %<+% full_data + 
  geom_tiplab(aes(label = project_id)) + 
  geom_tippoint(aes(color = specimen_source)) +
  geom_treescale() +
  theme(legend.position = "bottom", 
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10)) +
  ggtitle("Phylogenetic Tree Subsetted to Evergreen Rotary Park Seal Fecal Sample (AN0107)")

sub_tree = tree_subset(full_tree, node = "SRR12584072", levels_back = 4) #create subtree based on SRR12584072 seal fecal sample (AN0107)
ggtree(sub_tree) %<+% full_data + 
  geom_tiplab(aes(label = wgs_mlst)) + 
  geom_tippoint(aes(color = specimen_source)) +
  geom_treescale() +
  theme(legend.position = "bottom", 
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10)) +
  ggtitle("Phylogenetic Tree Subsetted to Evergreen Rotary Park Seal Fecal Sample (AN0107)")

sub_tree = tree_subset(full_tree, node = "SRR12584072", levels_back = 4) #create subtree based on SRR12584072 seal fecal sample (AN0107)
ggtree(sub_tree) %<+% full_data + 
  geom_tiplab(aes(label = srr_id)) + 
  geom_tippoint(aes(color = specimen_source)) +
  geom_treescale() +
  theme(legend.position = "bottom", 
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10)) +
  ggtitle("Phylogenetic Tree Subsetted to Evergreen Rotary Park Seal Fecal Sample (AN0107)")
```


# ST10 and ST 131 trees
```{r}
# ST10 phylogenetic tree
st10_phylotree = ggtree(st10_tree, size = 0.5)
st10_phylotree %<+% st10_data + 
  geom_tiplab(aes(label = Local_Specimen_Number), size = 5) + 
  geom_tippoint(aes(color = Source, size = 2)) + 
  geom_treescale() +
  theme(legend.position = "bottom", 
        legend.title = element_text(size = 18),
        legend.text = element_text(size = 15)) +
  ggtitle("ST10 Phylogenetic Tree")
  

# ST131 phylogenetic tree
st131_phylotree = ggtree(st131_tree, size = 0.5) 
st131_phylotree %<+% st131_data + 
  geom_tiplab(aes(label = Local_Specimen_Number), size = 5) + 
  geom_tippoint(aes(color = Source, size = 2)) +
  geom_treescale() +
  theme(legend.position = "bottom", 
        legend.title = element_text(size = 18),
        legend.text = element_text(size = 15)) +
  ggtitle("ST131 Phylogenetic Tree") 


#p = ggtree(tree) + geom_tiplab()
#viewClade(p, MRCA(p, tip = c("SRR10948144", "SRR10948217", "SRR11059190", "SRR11068080", "SRR11091347", "SRR11091350", "SRR11091351", "SRR11113566", "SRR11116097", "SRR11536635", "SRR11618038", "SRR11960632", "SRR12777351")))
```


